/**
 * The SDK reads a document produced by Python — including the report, which it must never
 * recompute. The fixture is generated by `scripts/generate.sh`, so a drift between the two sides
 * shows up here rather than in a UI.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  assertReadableVersion,
  countRelationsByKind,
  decisionLabel,
  detectSchemaVersion,
  findContradictedFindings,
  findObservablesAtLeast,
  findObservablesByVerdict,
  findUncountedFindings,
  generateDecisionKey,
  generateFindingKey,
  generateRelationKey,
  generateSignalKey,
  getAllDecisions,
  getAllObservables,
  getCounts,
  getDecisionFor,
  getEvidencesByType,
  getGlobalScore,
  getGlobalVerdict,
  getObservableGraph,
  getObservableResult,
  getObservableVerdict,
  getRootObservable,
  getTagAggregatedScore,
  getThreatIntelsFor,
  isAllowlisted,
  isCyvest,
  parseCyvest,
  parseKeyType,
  wasSuppressed,
} from "../src";
import type { Investigation } from "../src";

const fixturePath = fileURLToPath(new URL("./fixture.investigation.json", import.meta.url));
const investigation: Investigation = parseCyvest(JSON.parse(readFileSync(fixturePath, "utf-8")));

const URL_KEY = "obs:url:hxxp://bad.example/x";
const CDN_KEY = "obs:domain:cdn.partner.example";

describe("parsing and the version contract", () => {
  const raw = () => JSON.parse(readFileSync(fixturePath, "utf-8"));

  it("accepts a document produced by Python", () => {
    expect(isCyvest(JSON.parse(readFileSync(fixturePath, "utf-8")))).toBe(true);
  });

  it("refuses a newer document instead of ignoring unknown fields", () => {
    expect(() => assertReadableVersion("7.1.0")).toThrow(/upgrade/);
  });

  it("refuses an older document and points at the migration", () => {
    expect(() => assertReadableVersion("6.0.0")).toThrow(/migrate/);
  });

  it("accepts an earlier minor of the same major, which is what lets a 7.1 SDK read 7.0 data", () => {
    const document = raw();
    document.schema_version = "7.0.99";
    expect(() => parseCyvest(document)).not.toThrow();
  });

  // The checks above call the guard directly. These go through `parseCyvest`, which is what a
  // consumer actually calls.
  it("applies the version contract through parseCyvest, not just in isolation", () => {
    const document = raw();
    document.schema_version = "7.1.0";
    expect(() => parseCyvest(document)).toThrow(/newer than this SDK/);
  });

  it("points a v6 document at the migration rather than at a shape error", () => {
    const document = raw();
    document.schema_version = "6.0.0";
    expect(() => parseCyvest(document)).toThrow(/migrate/);
  });

  it("treats a document with no schema_version as pre-v7", () => {
    const document = raw();
    delete document.schema_version;
    expect(() => parseCyvest(document)).toThrow(/migrate/);
  });

  it("treats a non-semver schema_version as pre-v7", () => {
    const document = raw();
    document.schema_version = "seven";
    expect(detectSchemaVersion(document)).toBe("5");
    expect(() => parseCyvest(document)).toThrow(/migrate/);
  });

  it("reads the declared version when it is well formed", () => {
    expect(detectSchemaVersion(raw())).toBe("7.0.0");
  });
});

describe("results come from the report", () => {
  it("reads the global score without recomputing it", () => {
    expect(getGlobalScore(investigation)).toBe(12);
    expect(getGlobalVerdict(investigation)).toBe("MALICIOUS");
  });

  it("reads an observable verdict", () => {
    expect(getObservableVerdict(investigation, URL_KEY)).toBe("MALICIOUS");
    expect(getObservableResult(investigation, URL_KEY)?.score).toBe(6);
  });

  it("keys observable results by the observable key alone", () => {
    expect(Object.keys(investigation.report.observables ?? {})).toContain(URL_KEY);
  });

  it("aggregates a tag by summing what the engine produced", () => {
    expect(getTagAggregatedScore(investigation, "phishing")).toBe(6);
  });

  it("surfaces a value that a decision or a stronger link overrode", () => {
    expect(wasSuppressed(investigation, CDN_KEY)).toBe(true);
  });
});

describe("decisions", () => {
  it("exposes an allowlist as a declared act", () => {
    const decisions = Object.values(getAllDecisions(investigation));
    expect(decisions).toHaveLength(1);
    expect(decisions[0].kind).toBe("REFUTE");
    expect(decisions[0].justification).toBe("CDN partenaire");
    expect(decisions[0].source.name).toBe("alice");
  });

  it("names a stance the way the analyst who took it would", () => {
    const decision = getDecisionFor(investigation, CDN_KEY)!;
    expect(decisionLabel(decision)).toBe("ALLOWLISTED");
  });

  it("makes an allowlisted observable derive to SAFE", () => {
    expect(isAllowlisted(investigation, CDN_KEY)).toBe(true);
    expect(getObservableVerdict(investigation, CDN_KEY)).toBe("SAFE");
  });
});

describe("finders", () => {
  it("filters observables by computed verdict", () => {
    expect(findObservablesByVerdict(investigation, "MALICIOUS").map((o) => o.key)).toContain(URL_KEY);
    expect(findObservablesAtLeast(investigation, "SUSPICIOUS").length).toBeGreaterThan(0);
  });

  it("lists findings excluded from the score but still visible", () => {
    const uncounted = findUncountedFindings(investigation);
    expect(uncounted.map((f) => f.rule_id)).toContain("not_applicable");
  });

  it("lists findings whose own claim was outweighed by an observable", () => {
    expect(findContradictedFindings(investigation).map((f) => f.rule_id)).toContain("spf_pass");
  });

  it("finds the signals attached to an observable", () => {
    expect(getThreatIntelsFor(investigation, URL_KEY).map((s) => s.source.name)).toEqual(["virustotal"]);
  });
});

describe("graph", () => {
  it("builds nodes and edges without a direction field", () => {
    const graph = getObservableGraph(investigation);
    expect(graph.nodes.length).toBe(Object.keys(getAllObservables(investigation)).length);
    const extraction = graph.edges.find((edge) => edge.kind === "extraction");
    expect(extraction?.target).toBe(URL_KEY);
  });

  it("marks the edges that actually carried score", () => {
    const graph = getObservableGraph(investigation);
    expect(graph.edges.some((edge) => edge.carriedScore)).toBe(true);
  });

  it("counts relations by kind", () => {
    expect(Object.keys(countRelationsByKind(investigation))).toContain("extraction");
  });

  it("exposes the root through the header, not a magic value", () => {
    const root = getRootObservable(investigation);
    expect(root).toBeDefined();
    expect(root?.value).not.toBe("root");
  });
});

describe("evidence", () => {
  it("treats the v6 enrichment as an evidence type", () => {
    expect(getEvidencesByType(investigation, "enrichment").map((e) => e.title)).toContain("whois");
  });
});

describe("keys", () => {
  it("keeps the v6 signal format", () => {
    expect(generateSignalKey("virustotal", URL_KEY)).toBe(`sig:virustotal:${URL_KEY}`);
  });

  it("identifies a finding by its rule, split by an external id", () => {
    expect(generateFindingKey("url_in_body")).toBe("fnd:url_in_body");
    expect(generateFindingKey("url_in_body", URL_KEY)).toBe(`fnd:url_in_body:${URL_KEY}`);
  });

  it("carries direction inside a relation key", () => {
    expect(generateRelationKey("obs:a", "obs:b", "extraction")).not.toBe(
      generateRelationKey("obs:b", "obs:a", "extraction"),
    );
  });

  it("keys a decision by its target alone", () => {
    expect(generateDecisionKey(URL_KEY)).toBe(`dec:${URL_KEY}`);
  });

  it("recognizes the v7 prefixes and no longer knows enr:", () => {
    expect(parseKeyType("rel:extraction:obs:a>obs:b")).toBe("rel");
    expect(parseKeyType("dec:obs:a")).toBe("dec");
    expect(parseKeyType("enr:whois")).toBeNull();
  });
});

describe("counts", () => {
  it("separates total findings from those that actually count", () => {
    const counts = getCounts(investigation);
    expect(counts.findings).toBe(3);
    expect(counts.evaluatedFindings).toBe(2);
  });
});
