"""
Cyvest — cybersecurity investigation framework.

v7 rests on three layers: immutable **facts**, a declarative **policy**, and a pure
**evaluation** that recomputes a report instead of storing scores on the facts.
"""

from cyvest.autolink import AutoLink
from cyvest.compare import (
    DiffItem,
    DiffStatus,
    ExpectedResult,
    ObservableDiff,
    SignalDiff,
    compare_investigations,
)
from cyvest.cyvest import Cyvest, InvestigationSpec
from cyvest.enums import (
    Aggregation,
    Confidence,
    DecisionKind,
    Effect,
    LinkBasis,
    ObservableSubtype,
    ObservableType,
    RelationKind,
    Salience,
    SourceClass,
    Status,
    Tactic,
    Verdict,
    Weight,
)
from cyvest.errors import EngineMismatchError, PolicyMismatchError, RootMismatchError
from cyvest.evaluation import (
    Contribution,
    FindingResult,
    InvestigationResult,
    ObservableResult,
    Report,
    TimelineEntry,
    evaluate,
    verdict_from_score,
)
from cyvest.facts import (
    Decision,
    Evidence,
    Fact,
    Finding,
    Label,
    Observable,
    ObservableAlias,
    ObservableIdentity,
    ObservableLink,
    ObservableSignal,
    Relation,
    SourceRef,
    Tag,
    Taxonomy,
    ThreatIntel,
)
from cyvest.facts.store import MergeReport
from cyvest.io.markdown import render_llm_summary
from cyvest.io.serialization import merge_documents
from cyvest.operations import (
    AppliedOp,
    BatchResult,
    Operation,
    OpError,
    RecordBatch,
    aapply_operations,
    apply_operations,
)
from cyvest.policy import DEFAULT_POLICY, Policy
from cyvest.proxies import (
    DecisionProxy,
    EvidenceProxy,
    FindingProxy,
    ObservableProxy,
    TagProxy,
    ThreatIntelProxy,
)
from cyvest.relations import (
    RelationApplyResult,
    RelationContext,
    RelationIssue,
    RelationPlan,
    RelationPlanPreview,
    RelationProposal,
    apply_relation_plan,
    relation_context,
    validate_relation_plan,
)
from cyvest.resolvers import ObservableResolution, ObservableResolver, identity_is_complete, infer_observable_identity
from cyvest.schema.signal import SIGNAL_SCHEMA_VERSION, SignalEnvelope

__version__ = "7.1.0"

__all__ = [
    "DEFAULT_POLICY",
    "Aggregation",
    "AppliedOp",
    "AutoLink",
    "BatchResult",
    "OpError",
    "Operation",
    "RecordBatch",
    "RelationApplyResult",
    "RelationContext",
    "RelationIssue",
    "RelationPlan",
    "RelationPlanPreview",
    "RelationProposal",
    "aapply_operations",
    "apply_operations",
    "apply_relation_plan",
    "MergeReport",
    "PolicyMismatchError",
    "RootMismatchError",
    "identity_is_complete",
    "infer_observable_identity",
    "merge_documents",
    "relation_context",
    "render_llm_summary",
    "validate_relation_plan",
    "Confidence",
    "Contribution",
    "SIGNAL_SCHEMA_VERSION",
    "SignalEnvelope",
    "Cyvest",
    "InvestigationSpec",
    "DiffItem",
    "DiffStatus",
    "EngineMismatchError",
    "ExpectedResult",
    "ObservableDiff",
    "SignalDiff",
    "compare_investigations",
    "Decision",
    "DecisionKind",
    "DecisionProxy",
    "Effect",
    "Evidence",
    "EvidenceProxy",
    "Fact",
    "Finding",
    "FindingProxy",
    "FindingResult",
    "InvestigationResult",
    "Label",
    "LinkBasis",
    "Observable",
    "ObservableAlias",
    "ObservableIdentity",
    "ObservableLink",
    "ObservableProxy",
    "ObservableResolution",
    "ObservableResolver",
    "ObservableResult",
    "ObservableSignal",
    "ObservableSubtype",
    "ObservableType",
    "Policy",
    "Relation",
    "RelationKind",
    "Report",
    "Salience",
    "SourceClass",
    "SourceRef",
    "Status",
    "Tactic",
    "Tag",
    "TagProxy",
    "Taxonomy",
    "ThreatIntel",
    "ThreatIntelProxy",
    "TimelineEntry",
    "Verdict",
    "Weight",
    "evaluate",
    "verdict_from_score",
]
