"""
Serialization and chained migrations.

Migrations are **pure ``dict -> dict``** transforms. v6 ended its v5 migration by round-tripping
through the live object model, which tied it to models that no longer exist; nothing here
instantiates a fact until the very end.

Two traps are handled explicitly, and both are the same mistake: reading the *readable* field
instead of the *authoritative* one.

- Read ``score`` before ``level``. In v6 only the score propagates; the level is cosmetic and may
  contradict it, so migrating from the level inverts the sign on real data.
- Read ``direction`` before ``relationship_type``. It is the direction that governed propagation,
  and v6 allows ``EXTRACTION`` + ``BIDIRECTIONAL`` — an extraction that propagates nothing.
"""

from __future__ import annotations

import json
import re
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from cyvest.enums import DecisionKind, RelationKind, Scope, SourceClass, Status, Verdict
from cyvest.evaluation.projection import verdict_from_score
from cyvest.facts import (
    Decision,
    Evidence,
    Finding,
    Observable,
    ObservableLink,
    Relation,
    SourceRef,
    Tag,
    ThreatIntel,
)
from cyvest.facts.store import FactStore, InvestigationHeader
from cyvest.investigation import Investigation
from cyvest.model_schema import SCHEMA_VERSION, FactsSchema, InvestigationSchema
from cyvest.ulid import generate_ulid

MIGRATION_SOURCE = SourceRef(name="migration", source_class=SourceClass.ORG_POLICY)

_SEMVER = re.compile(r"^\d+\.\d+\.\d+$")

# v6 levels that leave the verdict axis entirely.
_LEVEL_TO_VERDICT = {
    "TRUSTED": Verdict.SAFE,
    "SAFE": Verdict.SAFE,
    "INFO": Verdict.INFO,
    "NOTABLE": Verdict.NOTABLE,
    "SUSPICIOUS": Verdict.SUSPICIOUS,
    "MALICIOUS": Verdict.MALICIOUS,
}


# --------------------------------------------------------------------------- serialize


def serialize_investigation(investigation: Investigation) -> InvestigationSchema:
    """Build the serialized document, report included — it is a required key."""
    store = investigation.store
    return InvestigationSchema(
        header=store.header,
        policy_version=investigation.policy.version,
        engine_id=store.header.engine_id,
        facts=FactsSchema(
            observables=dict(store.observables),
            relations=dict(store.relations),
            signals={key: signal for key, signal in store.signals.items() if isinstance(signal, ThreatIntel)},
            evidences=dict(store.evidences),
            findings=dict(store.findings),
        ),
        decisions=dict(store.decisions),
        tags=dict(store.tags),
        report=investigation.report,
    )


def investigation_to_dict(investigation: Investigation) -> dict[str, Any]:
    """Dump **by alias**: the JSON schema is generated by alias, so the document must match it."""
    return serialize_investigation(investigation).model_dump(mode="json", by_alias=True)


def save_investigation_json(investigation: Investigation, filepath: str | Path) -> None:
    """Trailing newline included, so a generated fixture does not fight `end-of-file-fixer`."""
    Path(filepath).write_text(
        json.dumps(investigation_to_dict(investigation), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# --------------------------------------------------------------------------- markdown


def generate_markdown_report(investigation: Investigation, *, include_tags: bool = True) -> str:
    """
    A human-readable report.

    Every figure comes from the report, and each one travels with the engine that produced it —
    comparing scores across engines is meaningless, so the id is never dropped.
    """
    report = investigation.report
    header = investigation.store.header
    lines: list[str] = [
        f"# {header.name or header.investigation_id}",
        "",
        f"- **Score**: {report.investigation.score:.2f} ({report.investigation.verdict.value})",
        f"- **Engine**: `{report.engine_id}` · policy `{report.policy_version}`",
        f"- **Opened**: {header.opened_at.isoformat()}",
        "",
    ]

    decisions = investigation.get_all_decisions()
    if decisions:
        lines += ["## Decisions", "", "| Target | Kind | By | Justification |", "|---|---|---|---|"]
        for decision in decisions.values():
            lines.append(
                f"| `{decision.target_key}` | {decision.kind.value} | {decision.source.name} "
                f"| {decision.justification or ''} |"
            )
        lines.append("")

    lines += ["## Findings", "", "| Rule | Score | Verdict | Status |", "|---|---|---|---|"]
    for key, finding in sorted(investigation.get_all_findings().items()):
        result = report.finding(key)
        if result is None:
            continue
        score = "—" if result.score is None else f"{result.score:.2f}"
        lines.append(
            f"| {finding.name or finding.rule_id} | {score} | {result.verdict.value} | {result.status.value} |"
        )
    lines.append("")

    lines += ["## Observables", "", "| Type | Value | Score | Verdict |", "|---|---|---|---|"]
    for key, observable in sorted(investigation.get_all_observables().items()):
        if key == header.root_key:
            continue
        result = report.observable(key)
        score = "—" if result is None or result.score is None else f"{result.score:.2f}"
        verdict = result.verdict.value if result else "INFO"
        lines.append(f"| {observable.obs_type} | `{observable.value}` | {score} | {verdict} |")
    lines.append("")

    if include_tags and investigation.get_all_tags():
        lines += ["## Tags", "", "| Tag | Aggregated score |", "|---|---|"]
        for tag in sorted(investigation.get_all_tags().values(), key=lambda t: t.name):
            lines.append(f"| {tag.name} | {investigation.get_tag_aggregated_score(tag.name):.2f} |")
        lines.append("")

    return "\n".join(lines)


def save_investigation_markdown(investigation: Investigation, filepath: str | Path, **kwargs: Any) -> str:
    Path(filepath).write_text(generate_markdown_report(investigation, **kwargs).rstrip("\n") + "\n", encoding="utf-8")
    return str(filepath)


# --------------------------------------------------------------------------- load


def detect_schema_version(data: dict[str, Any]) -> str:
    """
    Read the declared version, or fall back to ``"5"`` for documents that predate versioning.

    Any well-formed ``major.minor.patch`` is returned as-is — including versions newer than this
    library, which must be *refused* rather than mistaken for an ancient document.
    """
    version = str(data.get("schema_version", "")).strip()
    return version if _SEMVER.match(version) else "5"


def _version_tuple(version: str) -> tuple[int, int]:
    major, minor, *_ = version.split(".")
    return int(major), int(minor)


def _check_readable(version: str) -> None:
    """
    Upward compatibility only: we read older documents, never newer ones.

    Because of this rule a minor bump never needs a migration — fields added in 7.x are optional
    and carry defaults — which is what lets parsing stay strict.
    """
    if _version_tuple(version) > _version_tuple(SCHEMA_VERSION):
        raise ValueError(f"Document schema {version} is newer than this library ({SCHEMA_VERSION}); upgrade cyvest.")


def load_investigation_dict(data: dict[str, Any], *, migrate: bool = False) -> Investigation:
    """Rebuild an investigation. Migration is opt-in — no silent upgrade."""
    version = detect_schema_version(data)
    # Refuse a newer document before anything else: migrating it would be nonsense.
    _check_readable(version)

    if version != SCHEMA_VERSION:
        if not migrate:
            raise ValueError(
                f"Document schema is {version}, this library reads {SCHEMA_VERSION}. "
                "Pass migrate=True or run 'cyvest migrate'."
            )
        data = migrate_to_current(data)

    document = InvestigationSchema.model_validate(data)

    investigation = Investigation.__new__(Investigation)
    investigation.policy = _policy_for(document.policy_version)
    investigation.investigation_id = document.header.investigation_id
    investigation.fragment_id = document.header.investigation_id
    investigation.started_at = document.header.opened_at
    investigation.store = FactStore(document.header)
    investigation._report = None

    for collection in (
        document.facts.observables,
        document.facts.relations,
        document.facts.signals,
        document.facts.evidences,
        document.facts.findings,
        document.decisions,
        document.tags,
    ):
        investigation.store.extend(collection.values())

    return investigation


def _policy_for(policy_version: str) -> Any:
    from cyvest.policy import DEFAULT_POLICY

    if policy_version != DEFAULT_POLICY.version:
        raise ValueError(
            f"Unknown policy version {policy_version!r}. v7 ships a single policy; custom policies are not persisted."
        )
    return DEFAULT_POLICY


def load_investigation_json(filepath: str | Path, *, migrate: bool = False) -> Investigation:
    return load_investigation_dict(json.loads(Path(filepath).read_text(encoding="utf-8")), migrate=migrate)


# --------------------------------------------------------------------------- migrations


def _iso(value: Any, fallback: datetime) -> datetime:
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=UTC)
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return fallback
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=UTC)
    return fallback


def _envelope(fragment_id: str, asserted_at: datetime, source: SourceRef = MIGRATION_SOURCE) -> dict[str, Any]:
    return {
        "asserted_at": asserted_at,
        "seq": generate_ulid(timestamp_ms=int(asserted_at.timestamp() * 1000)),
        "source": source,
        "fragment_id": fragment_id,
    }


def _judgment_from_v6(payload: dict[str, Any]) -> dict[str, Any]:
    """
    Derive ``(verdict, weight, confidence)`` from a v6 record.

    The score is authoritative; the level only speaks when there is no score, since a v6 record
    may carry a level that contradicts its own score.
    """
    raw_score = payload.get("score")
    score = float(raw_score) if raw_score is not None else 0.0
    if score != 0.0:
        return {"verdict": verdict_from_score(score), "weight": abs(score), "confidence": 1.0}

    level = str(payload.get("level", "INFO")).upper()
    return {"verdict": _LEVEL_TO_VERDICT.get(level, Verdict.INFO), "weight": 0.0, "confidence": 1.0}


def _migrate_v5_to_v6(data: dict[str, Any]) -> dict[str, Any]:
    """Pure dict transform: inline the defaults v6 used to add through its models."""
    migrated = dict(data)
    migrated["schema_version"] = "6.0.0"
    migrated.pop("stats", None)

    for observable in (migrated.get("observables") or {}).values():
        observable.setdefault("internal", True)
        observable.setdefault("whitelisted", False)
        observable.setdefault("comment", "")
        observable.setdefault("extra", {})
        observable.setdefault("aliases", [])
        observable.setdefault("occurrence_count", 1)
        observable.setdefault("relationships", [])
        observable.setdefault("threat_intels", [])

    for finding in (migrated.get("findings") or {}).values():
        finding.setdefault("comment", "")
        finding.setdefault("extra", {})
        finding.setdefault("observable_links", [])

    return migrated


def _migrate_v6_to_v7(data: dict[str, Any]) -> dict[str, Any]:
    """Turn a v6 document into a v7 one, preserving its numbers exactly."""
    fragment_id = str(data.get("investigation_id") or generate_ulid())
    opened_at = _iso(data.get("started_at"), datetime.now(UTC))
    envelope = _envelope(fragment_id, opened_at)

    observables: dict[str, Any] = {}
    relations: dict[str, Any] = {}
    signals: dict[str, Any] = {}
    findings: dict[str, Any] = {}
    decisions: dict[str, Any] = {}
    evidences: dict[str, Any] = {}
    tags: dict[str, Any] = {}

    root_key = None
    for key, payload in (data.get("observables") or {}).items():
        if payload.get("value") == "root":
            root_key = key
        observable = Observable(
            type=payload.get("type") or payload.get("obs_type"),
            subtype=payload.get("subtype"),
            namespace=payload.get("namespace"),
            value=payload["value"],
            internal=bool(payload.get("internal", True)),
            comment=payload.get("comment", ""),
            extra=payload.get("extra") or {},
            occurrences={fragment_id: int(payload.get("occurrence_count", 1))},
            **envelope,
        )
        observables[observable.key] = observable

        if payload.get("whitelisted"):
            decision = Decision(
                target_key=observable.key,
                kind=DecisionKind.ALLOWLISTED,
                justification="migrated from v6 whitelisted flag",
                **envelope,
            )
            decisions[decision.key] = decision

        for raw in payload.get("relationships") or []:
            relation = _migrate_relationship(raw, source_key=key, envelope=envelope)
            if relation is not None:
                relations[relation.key] = relation

    for key, payload in (data.get("threat_intels") or {}).items():
        subject_key = payload.get("observable_key") or _subject_from_ti_key(key)
        if subject_key is None:
            continue
        signal = ThreatIntel(
            subject_key=subject_key,
            source=SourceRef(name=payload.get("source", "unknown"), source_class=SourceClass.VENDOR_FEED),
            taxonomies=tuple(
                item.get("name", "") if isinstance(item, dict) else str(item)
                for item in (payload.get("taxonomies") or [])
            ),
            comment=payload.get("comment", ""),
            asserted_at=envelope["asserted_at"],
            seq=envelope["seq"],
            fragment_id=fragment_id,
            **_judgment_from_v6(payload),
        )
        signals[signal.key] = signal

    for payload in (data.get("evidences") or {}).values():
        evidence = Evidence(
            evidence_type=payload.get("evidence_type", "artifact"),
            title=payload.get("title", ""),
            content=payload.get("content"),
            uri=payload.get("uri"),
            external_id=payload.get("external_id"),
            source=SourceRef(name=payload.get("source", "legacy"), source_class=SourceClass.INTERNAL_TOOL),
            asserted_at=envelope["asserted_at"],
            seq=envelope["seq"],
            fragment_id=fragment_id,
        )
        evidences[evidence.key] = evidence

    # v6 enrichments are evidence that happened to have a dedicated type.
    for payload in (data.get("enrichments") or {}).values():
        evidence = Evidence(
            evidence_type="enrichment",
            title=payload.get("name", ""),
            content=payload.get("data"),
            source=SourceRef(
                name=payload.get("context") or "legacy",
                source_class=SourceClass.INTERNAL_TOOL,
            ),
            asserted_at=envelope["asserted_at"],
            seq=envelope["seq"],
            fragment_id=fragment_id,
        )
        evidences[evidence.key] = evidence

    for payload in (data.get("findings") or {}).values():
        links = tuple(
            ObservableLink(
                observable_key=link["observable_key"],
                scope=Scope.ALL if str(link.get("propagation_mode", "")).upper() == "GLOBAL" else Scope.OWN_FRAGMENT,
            )
            for link in payload.get("observable_links") or []
        )
        judgment = _judgment_from_v6(payload)
        # A v6 finding stuck at NONE never applied; keep it visible but out of the arithmetic.
        status = Status.NOT_APPLICABLE if str(payload.get("level", "")).upper() == "NONE" else Status.EVALUATED
        finding = Finding(
            rule_id=payload.get("finding_name", "unknown"),
            name=payload.get("description", ""),
            comment=payload.get("comment", ""),
            subject_key=links[0].observable_key if links else (root_key or fragment_id),
            observable_links=links,
            status=status,
            extra=payload.get("extra") or {},
            evidence_keys=tuple(link["evidence_key"] for link in payload.get("evidence_links") or []),
            asserted_at=envelope["asserted_at"],
            seq=envelope["seq"],
            source=MIGRATION_SOURCE,
            fragment_id=fragment_id,
            **judgment,
        )
        findings[finding.key] = finding

    for payload in (data.get("tags") or {}).values():
        tag = Tag(
            name=payload["name"],
            description=payload.get("description", ""),
            finding_keys=tuple(
                item["key"] if isinstance(item, dict) else str(item) for item in payload.get("findings") or []
            ),
            **envelope,
        )
        tags[tag.key] = tag

    for payload in data.get("whitelists") or []:
        target = payload.get("identifier")
        if target in observables:
            decision = Decision(
                target_key=target,
                kind=DecisionKind.ALLOWLISTED,
                justification=payload.get("justification"),
                **envelope,
            )
            decisions[decision.key] = decision

    header = InvestigationHeader(
        investigation_id=fragment_id,
        name=str(data.get("investigation_name") or ""),
        root_key=root_key,
        opened_at=opened_at,
        policy_version="default-v1",
        engine_id="basic-v1",
        fragment_ids=(fragment_id,),
    )

    document = InvestigationSchema(
        header=header,
        facts=FactsSchema(
            observables=observables,
            relations=relations,
            signals=signals,
            evidences=evidences,
            findings=findings,
        ),
        decisions=decisions,
        tags=tags,
        report=_empty_report(header),
    )
    migrated = document.model_dump(mode="json", by_alias=True)

    # The report is derived, so rebuild it from the migrated facts rather than trusting v6's.
    rebuilt = load_investigation_dict(migrated)
    migrated["report"] = rebuilt.report.model_dump(mode="json", by_alias=True)
    return migrated


def _empty_report(header: InvestigationHeader) -> Any:
    from cyvest.evaluation.report import InvestigationResult, Report

    return Report(
        engine_id=header.engine_id,
        policy_version=header.policy_version,
        investigation=InvestigationResult(key=header.investigation_id, score=0.0),
    )


def _subject_from_ti_key(key: str) -> str | None:
    """``ti:{source}:{observable_key}`` — the observable key is everything past the source."""
    parts = key.split(":", 2)
    return parts[2] if len(parts) == 3 else None


def _migrate_relationship(raw: dict[str, Any], *, source_key: str, envelope: dict[str, Any]) -> Relation | None:
    """
    ⚠ Read ``direction`` first.

    v6 does not forbid ``EXTRACTION`` + ``BIDIRECTIONAL``, and that combination propagated
    nothing. Reading the type first would make it propagate in v7 — a silent parity break.
    """
    target_key = raw.get("target_key")
    if not target_key:
        return None

    direction = str(raw.get("direction", "outbound")).lower()
    raw_type = str(raw.get("relationship_type", "related-to")).lower()

    if direction == "bidirectional":
        kind, parent, child = RelationKind.RELATED_TO, source_key, target_key
    elif direction == "inbound":
        kind, parent, child = RelationKind(raw_type), target_key, source_key
    else:
        kind, parent, child = RelationKind(raw_type), source_key, target_key

    return Relation(
        source_key=parent,
        target_key=child,
        kind=kind,
        comment=raw.get("comment", ""),
        **envelope,
    )


_MIGRATIONS = {
    "5": ("6.0.0", _migrate_v5_to_v6),
    "6.0.0": ("7.0.0", _migrate_v6_to_v7),
}


def migrate_to_current(data: dict[str, Any]) -> dict[str, Any]:
    """Chain migrations up to the current schema, so a 5.x document upgrades in one call."""
    version = detect_schema_version(data)
    migrated = data
    while version != SCHEMA_VERSION:
        step = _MIGRATIONS.get(version)
        if step is None:
            raise ValueError(f"No migration path from schema version {version!r}")
        target, transform = step
        migrated = transform(migrated)
        version = target
    return migrated


__all__ = [
    "SCHEMA_VERSION",
    "detect_schema_version",
    "investigation_to_dict",
    "load_investigation_dict",
    "load_investigation_json",
    "migrate_to_current",
    "save_investigation_json",
    "serialize_investigation",
]
