"""
Serialization and chained migrations.

Migrations are **pure ``dict -> dict``** transforms. v6 ended its v5 migration by round-tripping
through the live object model, which tied it to models that no longer exist; nothing here
instantiates a fact until the very end.

Two traps are handled explicitly, and both are the same mistake: reading the *readable* field
instead of the *authoritative* one.

- Read ``score`` before ``level``. In v6 only the score propagates; the level is cosmetic and may
  contradict it, so migrating from the level inverts the sign on real data.
- Read ``direction`` before ``relationship_type``. It is the direction that governed propagation,
  and v6 allows ``EXTRACTION`` + ``BIDIRECTIONAL`` — an extraction that propagates nothing.
"""

from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from cyvest.enums import DecisionKind, LinkBasis, RelationKind, SourceClass, Status, Verdict
from cyvest.evaluation.projection import verdict_from_score
from cyvest.facts import (
    Decision,
    Evidence,
    Finding,
    Observable,
    ObservableLink,
    Relation,
    SourceRef,
    Tag,
    Taxonomy,
    ThreatIntel,
)
from cyvest.facts.store import FactStore, InvestigationHeader
from cyvest.investigation import Investigation
from cyvest.schema.investigation import SCHEMA_VERSION, FactsSchema, InvestigationSchema
from cyvest.ulid import generate_ulid

MIGRATION_SOURCE = SourceRef(name="migration", source_class=SourceClass.ORG_POLICY)

_SEMVER = re.compile(r"^\d+\.\d+\.\d+$")

# v6 levels that leave the verdict axis entirely.
_LEVEL_TO_VERDICT = {
    "TRUSTED": Verdict.SAFE,
    "SAFE": Verdict.SAFE,
    "INFO": Verdict.INFO,
    "NOTABLE": Verdict.NOTABLE,
    "SUSPICIOUS": Verdict.SUSPICIOUS,
    "MALICIOUS": Verdict.MALICIOUS,
}


# --------------------------------------------------------------------------- serialize


def serialize_investigation(investigation: Investigation) -> InvestigationSchema:
    """Build the serialized document, report included — it is a required key."""
    store = investigation.store
    return InvestigationSchema(
        header=store.header,
        policy_version=investigation.policy.version,
        engine_id=store.header.engine_id,
        facts=FactsSchema(
            observables=dict(store.observables),
            relations=dict(store.relations),
            signals={key: signal for key, signal in store.signals.items() if isinstance(signal, ThreatIntel)},
            evidences=dict(store.evidences),
            findings=dict(store.findings),
        ),
        decisions=dict(store.decisions),
        tags=dict(store.tags),
        report=investigation.report,
    )


def investigation_to_dict(investigation: Investigation) -> dict[str, Any]:
    """Dump **by alias**: the JSON schema is generated by alias, so the document must match it."""
    return serialize_investigation(investigation).model_dump(mode="json", by_alias=True)


def save_investigation_json(investigation: Investigation, filepath: str | Path) -> None:
    """Trailing newline included, so a generated fixture does not fight `end-of-file-fixer`."""
    Path(filepath).write_text(
        json.dumps(investigation_to_dict(investigation), indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


# --------------------------------------------------------------------------- merge

_FACT_COLLECTIONS = ("observables", "relations", "signals", "evidences", "findings")
_TOP_LEVEL_COLLECTIONS = ("decisions", "tags")


def _fact_items(document: dict[str, Any]) -> dict[str, Any]:
    """Every fact of a document keyed by its semantic key, whatever collection it sits in."""
    items: dict[str, Any] = {}
    facts = document.get("facts") or {}
    for name in _FACT_COLLECTIONS:
        items.update(facts.get(name) or {})
    for name in _TOP_LEVEL_COLLECTIONS:
        items.update(document.get(name) or {})
    return items


def _subsumes(bigger: dict[str, Any], smaller: dict[str, Any]) -> bool:
    """
    ``bigger`` already contains every fact of ``smaller``, unchanged, under the same identity.

    Facts are compared whole rather than by ``seq``: an observable keeps its ``seq`` through a
    merge while its per-fragment counters grow, so equal sequence numbers do not mean equal facts.
    """
    big_header = bigger.get("header") or {}
    small_header = smaller.get("header") or {}
    if big_header.get("investigation_id") != small_header.get("investigation_id"):
        return False
    if not set(small_header.get("fragment_ids") or ()) <= set(big_header.get("fragment_ids") or ()):
        return False
    big_items = _fact_items(bigger)
    return all(big_items.get(key) == fact for key, fact in _fact_items(smaller).items())


def merge_documents(current: dict[str, Any] | None, incoming: dict[str, Any] | None) -> dict[str, Any] | None:
    """
    The union of two serialized documents — the reducer an agent framework folds its state with.

    Same law as ``FactStore.union``, so the same properties; no facade has to be alive at the
    merge site. Either side may be missing. Two fast paths keep the common case cheap: identical
    documents come back as is, and a document that contains everything the other does wins on a
    dict comparison — which is what every step of a sequential run produces, since each write
    starts from the previous state. Only genuinely divergent documents pay for a model load.
    """
    if not current:
        return incoming or None
    if not incoming:
        return current
    if current is incoming or current == incoming:
        return current
    if _subsumes(incoming, current):
        return incoming
    if _subsumes(current, incoming):
        return current
    first, second = load_investigation_dict(current), load_investigation_dict(incoming)
    return investigation_to_dict(Investigation.from_store(first.store.union(second.store), policy=first.policy))


# --------------------------------------------------------------------------- load


def detect_schema_version(data: dict[str, Any]) -> str:
    """
    Read the declared version, or fall back to ``"5"`` for documents that predate versioning.

    Any well-formed ``major.minor.patch`` is returned as-is — including versions newer than this
    library, which must be *refused* rather than mistaken for an ancient document.
    """
    version = str(data.get("schema_version", "")).strip()
    return version if _SEMVER.match(version) else "5"


def _version_tuple(version: str) -> tuple[int, int]:
    """
    Split a version into ``(major, minor)``.

    ``"5"`` is a legitimate input, not a malformed one: unversioned documents predate the
    ``major.minor.patch`` convention and :func:`detect_schema_version` reports them as bare
    ``"5"``. Unpacking two parts unconditionally made every v5 document unloadable — including
    through ``migrate=True``, since the readability check runs before the migration.
    """
    major, _, remainder = version.partition(".")
    minor, _, _patch = remainder.partition(".")
    return int(major), int(minor or 0)


def _check_readable(version: str) -> None:
    """
    Upward compatibility only: we read older documents, never newer ones.

    Older minor shapes are normalized by their models (notably the 7.0 taxonomy strings).
    Unknown fields still fail validation instead of being silently discarded.
    """
    if _version_tuple(version) > _version_tuple(SCHEMA_VERSION):
        raise ValueError(f"Document schema {version} is newer than this library ({SCHEMA_VERSION}); upgrade cyvest.")


def load_investigation_dict(data: dict[str, Any], *, migrate: bool = False) -> Investigation:
    """Rebuild an investigation. Migration is opt-in — no silent upgrade."""
    version = detect_schema_version(data)
    # Refuse a newer document before anything else: migrating it would be nonsense.
    _check_readable(version)

    # Major migrations are opt-in. Older minor shapes are accepted by model validators.
    if _version_tuple(version)[0] != _version_tuple(SCHEMA_VERSION)[0]:
        if not migrate:
            raise ValueError(
                f"Document schema is {version}, this library reads {SCHEMA_VERSION}. "
                "Pass migrate=True or run 'cyvest migrate'."
            )
        data = migrate_to_current(data)

    document = InvestigationSchema.model_validate(data)

    store = FactStore(document.header)
    for collection in (
        document.facts.observables,
        document.facts.relations,
        document.facts.signals,
        document.facts.evidences,
        document.facts.findings,
        document.decisions,
        document.tags,
    ):
        store.extend(collection.values())

    return Investigation.from_store(store, policy=_policy_for(document.policy_version))


def _policy_for(policy_version: str) -> Any:
    from cyvest.policy import DEFAULT_POLICY

    if policy_version != DEFAULT_POLICY.version:
        raise ValueError(
            f"Unknown policy version {policy_version!r}. v7 ships a single policy; custom policies are not persisted."
        )
    return DEFAULT_POLICY


def load_investigation_json(filepath: str | Path, *, migrate: bool = False) -> Investigation:
    return load_investigation_dict(json.loads(Path(filepath).read_text(encoding="utf-8")), migrate=migrate)


# --------------------------------------------------------------------------- migrations


def _iso(value: Any, fallback: datetime) -> datetime:
    if isinstance(value, datetime):
        return value if value.tzinfo else value.replace(tzinfo=timezone.utc)
    if isinstance(value, str):
        try:
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
        except ValueError:
            return fallback
        return parsed if parsed.tzinfo else parsed.replace(tzinfo=timezone.utc)
    return fallback


def _translated(key_map: dict[str, str], key: str) -> str:
    """
    Map a v6 observable key onto the key v7 regenerates for the same observable.

    Unknown keys pass through unchanged: a reference this migration cannot place is better left
    as it was than rewritten into something equally wrong but harder to recognize.
    """
    return key_map.get(key, key)


def _envelope(fragment_id: str, asserted_at: datetime, source: SourceRef = MIGRATION_SOURCE) -> dict[str, Any]:
    """
    Build a fresh envelope for **one** migrated fact.

    Called per fact, never hoisted: ``seq`` is the ULID that orders facts and breaks merge ties,
    so reusing a single one across a whole document would leave every migrated fact tied with
    every other and make ``resolve_conflict`` arbitrary between them.
    """
    return {
        "asserted_at": asserted_at,
        "seq": generate_ulid(timestamp_ms=int(asserted_at.timestamp() * 1000)),
        "source": source,
        "fragment_id": fragment_id,
    }


def _judgment_from_v6(payload: dict[str, Any]) -> dict[str, Any]:
    """
    Derive ``(verdict, weight, confidence)`` from a v6 record.

    The score is authoritative; the level only speaks when there is no score, since a v6 record
    may carry a level that contradicts its own score.
    """
    raw_score = payload.get("score")
    score = float(raw_score) if raw_score is not None else 0.0
    if score != 0.0:
        return {"verdict": verdict_from_score(score), "weight": abs(score), "confidence": 1.0}

    level = str(payload.get("level", "INFO")).upper()
    return {"verdict": _LEVEL_TO_VERDICT.get(level, Verdict.INFO), "weight": 0.0, "confidence": 1.0}


def _migrate_v5_to_v6(data: dict[str, Any]) -> dict[str, Any]:
    """Pure dict transform: inline the defaults v6 used to add through its models."""
    migrated = dict(data)
    migrated["schema_version"] = "6.0.0"
    migrated.pop("stats", None)

    for observable in (migrated.get("observables") or {}).values():
        observable.setdefault("internal", True)
        observable.setdefault("whitelisted", False)
        observable.setdefault("comment", "")
        observable.setdefault("extra", {})
        observable.setdefault("aliases", [])
        observable.setdefault("occurrence_count", 1)
        observable.setdefault("relationships", [])
        observable.setdefault("threat_intels", [])

    for finding in (migrated.get("findings") or {}).values():
        finding.setdefault("comment", "")
        finding.setdefault("extra", {})
        finding.setdefault("observable_links", [])

    return migrated


def _migrate_v6_to_v7(data: dict[str, Any]) -> dict[str, Any]:
    """Turn a v6 document into a v7 one, preserving its numbers exactly."""
    fragment_id = str(data.get("investigation_id") or generate_ulid())
    opened_at = _iso(data.get("started_at"), datetime.now(timezone.utc))

    observables: dict[str, Any] = {}
    relations: dict[str, Any] = {}
    signals: dict[str, Any] = {}
    findings: dict[str, Any] = {}
    decisions: dict[str, Any] = {}
    evidences: dict[str, Any] = {}
    tags: dict[str, Any] = {}

    root_key = None
    # v6 keys are not always what v7 regenerates — the value is normalized now, so
    # `obs:domain:EVIL.com` becomes `obs:domain:evil.com`. Every cross-reference below is
    # translated through this map instead of being reused verbatim: a stale key silently detaches
    # a signal or a link from its observable, and the migrated score stops matching v6.
    key_map: dict[str, str] = {}
    for key, payload in (data.get("observables") or {}).items():
        observable = Observable(
            type=payload.get("type") or payload.get("obs_type"),
            subtype=payload.get("subtype"),
            namespace=payload.get("namespace"),
            value=payload["value"],
            internal=bool(payload.get("internal", True)),
            comment=payload.get("comment", ""),
            extra=payload.get("extra") or {},
            occurrences={fragment_id: int(payload.get("occurrence_count", 1))},
            **_envelope(fragment_id, opened_at),
        )
        observables[observable.key] = observable
        key_map[key] = observable.key
        # Read the regenerated key, not the v6 one: the header must point at a key that exists
        # in the migrated document.
        if payload.get("value") == "root":
            root_key = observable.key

        if payload.get("whitelisted"):
            decision = Decision(
                target_key=observable.key,
                kind=DecisionKind.REFUTE,
                justification="migrated from v6 whitelisted flag",
                **_envelope(fragment_id, opened_at),
            )
            decisions[decision.key] = decision

    # Relations come in a second pass: a relationship may point at an observable declared later
    # in the document, whose regenerated key is only known once every observable is built.
    for key, payload in (data.get("observables") or {}).items():
        for raw in payload.get("relationships") or []:
            relation = _migrate_relationship(
                raw,
                source_key=_translated(key_map, key),
                key_map=key_map,
                envelope=_envelope(fragment_id, opened_at),
            )
            if relation is not None:
                relations[relation.key] = relation

    for key, payload in (data.get("threat_intels") or {}).items():
        subject_key = payload.get("observable_key") or _subject_from_ti_key(key)
        if subject_key is None:
            continue
        signal = ThreatIntel(
            subject_key=_translated(key_map, subject_key),
            taxonomies=tuple(
                Taxonomy(
                    name=item["name"],
                    value=item["value"],
                    verdict=_LEVEL_TO_VERDICT.get(str(item.get("level", "INFO")).upper(), Verdict.INFO),
                )
                if isinstance(item, dict)
                else Taxonomy.model_validate(item)
                for item in (payload.get("taxonomies") or [])
            ),
            comment=payload.get("comment", ""),
            **_envelope(
                fragment_id,
                opened_at,
                SourceRef(name=payload.get("source", "unknown"), source_class=SourceClass.VENDOR_FEED),
            ),
            **_judgment_from_v6(payload),
        )
        signals[signal.key] = signal

    for payload in (data.get("evidences") or {}).values():
        evidence = Evidence(
            evidence_type=payload.get("evidence_type", "artifact"),
            title=payload.get("title", ""),
            content=payload.get("content"),
            uri=payload.get("uri"),
            external_id=payload.get("external_id"),
            **_envelope(
                fragment_id,
                opened_at,
                SourceRef(name=payload.get("source", "legacy"), source_class=SourceClass.INTERNAL_TOOL),
            ),
        )
        evidences[evidence.key] = evidence

    # v6 enrichments are evidence that happened to have a dedicated type.
    for payload in (data.get("enrichments") or {}).values():
        evidence = Evidence(
            evidence_type="enrichment",
            title=payload.get("name", ""),
            content=payload.get("data"),
            **_envelope(
                fragment_id,
                opened_at,
                SourceRef(name=payload.get("context") or "legacy", source_class=SourceClass.INTERNAL_TOOL),
            ),
        )
        evidences[evidence.key] = evidence

    # v6 keyed a finding on its name, v7 on its `rule_id` — the same string, so the shape is
    # preserved. A tag still points at the old key, so it needs the same translation the
    # observables get.
    finding_key_map: dict[str, str] = {}
    for key, payload in (data.get("findings") or {}).items():
        # ⚠ v6 gated a LOCAL_ONLY link on ``origin_investigation_id == investigation_id``, so an
        # imported one was simply inert. v7 states that as ``LinkBasis.NONE``, decided here rather
        # than at evaluation: reading it as a live link would silently raise the score of every
        # merged investigation.
        origin = str(payload.get("origin_investigation_id") or fragment_id)
        native = origin == fragment_id
        links = tuple(
            ObservableLink(
                observable_key=_translated(key_map, link["observable_key"]),
                basis=LinkBasis.OBSERVABLE
                if str(link.get("propagation_mode", "")).upper() == "GLOBAL" or native
                else LinkBasis.NONE,
            )
            for link in payload.get("observable_links") or []
        )
        judgment = _judgment_from_v6(payload)
        # A v6 finding stuck at NONE never applied; keep it visible but out of the arithmetic.
        status = Status.NOT_APPLICABLE if str(payload.get("level", "")).upper() == "NONE" else Status.EVALUATED
        finding = Finding(
            rule_id=payload.get("finding_name", "unknown"),
            name=payload.get("description", ""),
            comment=payload.get("comment", ""),
            observable_links=links,
            status=status,
            extra=payload.get("extra") or {},
            evidence_keys=tuple(link["evidence_key"] for link in payload.get("evidence_links") or []),
            **_envelope(origin, opened_at),
            **judgment,
        )
        findings[finding.key] = finding
        finding_key_map[key] = finding.key

    for payload in (data.get("tags") or {}).values():
        tag = Tag(
            name=payload["name"],
            description=payload.get("description", ""),
            finding_keys=tuple(
                _translated(finding_key_map, item["key"] if isinstance(item, dict) else str(item))
                for item in payload.get("findings") or []
            ),
            **_envelope(fragment_id, opened_at),
        )
        tags[tag.key] = tag

    _migrate_whitelists(data, observables, decisions, evidences, key_map, fragment_id, opened_at)

    # Findings carry their origin fragment, so the header must list every fragment present.
    fragment_ids = dict.fromkeys([fragment_id, *(finding.fragment_id for finding in findings.values())])

    header = InvestigationHeader(
        investigation_id=fragment_id,
        name=str(data.get("investigation_name") or ""),
        root_key=root_key,
        opened_at=opened_at,
        policy_version="default-v1",
        engine_id="basic-v1",
        fragment_ids=tuple(fragment_ids),
    )

    document = InvestigationSchema(
        header=header,
        facts=FactsSchema(
            observables=observables,
            relations=relations,
            signals=signals,
            evidences=evidences,
            findings=findings,
        ),
        decisions=decisions,
        tags=tags,
        report=_empty_report(header),
    )
    migrated = document.model_dump(mode="json", by_alias=True)

    # The report is derived, so rebuild it from the migrated facts rather than trusting v6's.
    rebuilt = load_investigation_dict(migrated)
    migrated["report"] = rebuilt.report.model_dump(mode="json", by_alias=True)
    return migrated


def _migrate_whitelists(
    data: dict[str, Any],
    observables: dict[str, Any],
    decisions: dict[str, Any],
    evidences: dict[str, Any],
    key_map: dict[str, str],
    fragment_id: str,
    opened_at: datetime,
) -> None:
    """
    Carry v6 whitelist entries over.

    A v6 whitelist is investigation-level and its ``identifier`` is a free-form string, so only
    some entries name an observable. Those become an ``ALLOWLISTED`` decision on it, which is
    exactly what v6 meant by them.

    The rest — a ticket reference, an analyst note — name nothing v7 can bound, and are kept as
    **evidence** rather than as a decision on the root. ``ALLOWLISTED`` is not inert: it caps its
    target's score and marks every contribution on it unretained. Parking these entries there
    would manufacture a verdict nobody asserted, out of a string that had no scoring effect in v6
    either. Evidence keeps the analyst's words without inventing a claim.
    """
    unplaceable: list[dict[str, str]] = []

    for payload in data.get("whitelists") or []:
        identifier = str(payload.get("identifier") or "")
        target = _translated(key_map, identifier)
        if target in observables:
            decision = Decision(
                target_key=target,
                kind=DecisionKind.REFUTE,
                # v6 let a whitelist carry no reason. v7 requires one, so migration states the
                # truth it has — that the entry predates the requirement — rather than failing.
                justification=str(payload.get("justification") or "migrated from a v6 whitelist entry"),
                **_envelope(fragment_id, opened_at),
            )
            decisions[decision.key] = decision
            continue
        unplaceable.append(
            {
                "identifier": identifier,
                "name": str(payload.get("name") or ""),
                "justification": str(payload.get("justification") or ""),
            }
        )

    if not unplaceable:
        return

    # One evidence holding every entry: separate ones would collide on their content-derived key
    # whenever two entries read alike, and an analyst's note is not something to drop on the floor.
    evidence = Evidence(
        evidence_type="legacy_whitelist",
        title="v6 investigation whitelist",
        content=unplaceable,
        **_envelope(fragment_id, opened_at),
    )
    evidences[evidence.key] = evidence


def _empty_report(header: InvestigationHeader) -> Any:
    from cyvest.evaluation.report import InvestigationResult, Report

    return Report(
        engine_id=header.engine_id,
        policy_version=header.policy_version,
        investigation=InvestigationResult(key=header.investigation_id, score=0.0),
    )


def _subject_from_ti_key(key: str) -> str | None:
    """v6 form ``ti:{source}:{observable_key}`` — the observable key is everything past the source."""
    parts = key.split(":", 2)
    return parts[2] if len(parts) == 3 else None


def _migrate_relationship(
    raw: dict[str, Any],
    *,
    source_key: str,
    key_map: dict[str, str],
    envelope: dict[str, Any],
) -> Relation | None:
    """
    ⚠ Read ``direction`` first.

    v6 does not forbid ``EXTRACTION`` + ``BIDIRECTIONAL``, and that combination propagated
    nothing. Reading the type first would make it propagate in v7 — a silent parity break.
    """
    target_key = raw.get("target_key")
    if not target_key:
        return None
    target_key = _translated(key_map, target_key)

    direction = str(raw.get("direction", "outbound")).lower()
    raw_type = str(raw.get("relationship_type", "related-to")).lower()
    comment = str(raw.get("comment") or "")

    # v6 accepted any string as a type (``redirects-to``, ``resolves-to``…). v7's kinds are a
    # closed set, and an edge whose propagation v6 never defined must not start propagating here:
    # it becomes the inert ``related-to``, and the original type is kept on the comment so a
    # reader can still tell what the producer meant.
    try:
        typed_kind = RelationKind(raw_type)
    except ValueError:
        typed_kind = RelationKind.RELATED_TO
        comment = comment or raw_type

    if direction == "bidirectional":
        kind, parent, child = RelationKind.RELATED_TO, source_key, target_key
    elif direction == "inbound":
        kind, parent, child = typed_kind, target_key, source_key
    else:
        kind, parent, child = typed_kind, source_key, target_key

    return Relation(
        source_key=parent,
        target_key=child,
        kind=kind,
        comment=comment,
        **envelope,
    )


_MIGRATIONS = {
    "5": ("6.0.0", _migrate_v5_to_v6),
    "6.0.0": ("7.0.0", _migrate_v6_to_v7),
}


def migrate_to_current(data: dict[str, Any]) -> dict[str, Any]:
    """Chain major migrations, then normalize older minor shapes without recomputing reports."""
    version = detect_schema_version(data)
    _check_readable(version)
    migrated = data
    # Major rewrites have explicit transforms; minor normalization lives on the models.
    while _version_tuple(version)[0] != _version_tuple(SCHEMA_VERSION)[0]:
        step = _MIGRATIONS.get(version)
        if step is None:
            raise ValueError(f"No migration path from schema version {version!r}")
        target, transform = step
        migrated = transform(migrated)
        version = target
    if _version_tuple(version) < _version_tuple(SCHEMA_VERSION):
        migrated = InvestigationSchema.model_validate(migrated).model_dump(mode="json", by_alias=True)
        migrated["schema_version"] = SCHEMA_VERSION
    return migrated


__all__ = [
    "SCHEMA_VERSION",
    "detect_schema_version",
    "investigation_to_dict",
    "load_investigation_dict",
    "load_investigation_json",
    "merge_documents",
    "migrate_to_current",
    "save_investigation_json",
    "serialize_investigation",
]
